<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Общение");
?> <?$APPLICATION->IncludeComponent("bitrix:socialnetwork", ".default", array(
	"ITEM_DETAIL_COUNT" => "32",
	"ITEM_MAIN_COUNT" => "6",
	"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
	"NAME_TEMPLATE" => "",
	"SHOW_LOGIN" => "Y",
	"CAN_OWNER_EDIT_DESKTOP" => "Y",
	"GROUP_USE_KEYWORDS" => "Y",
	"SM_THEME" => "blue",
	"USE_MAIN_MENU" => "N",
	"SHOW_RATING" => "",
	"RATING_ID" => array(
	),
	"RATING_TYPE" => "",
	"PATH_TO_SEARCH_EXTERNAL" => "",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/social/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_TIME_LONG" => "604800",
	"PATH_TO_SMILE" => "/bitrix/images/socialnetwork/smile/",
	"PATH_TO_BLOG_SMILE" => "/bitrix/images/blog/smile/",
	"PATH_TO_FORUM_SMILE" => "/bitrix/images/forum/smile/",
	"SONET_PATH_TO_FORUM_ICON" => "/bitrix/images/forum/icon/",
	"SET_TITLE" => "Y",
	"SET_NAV_CHAIN" => "Y",
	"LOG_SUBSCRIBE_ONLY" => "N",
	"LOG_RSS_TTL" => "60",
	"USER_FIELDS_MAIN" => array(
	),
	"USER_PROPERTY_MAIN" => array(
	),
	"USER_FIELDS_CONTACT" => array(
	),
	"USER_PROPERTY_CONTACT" => array(
	),
	"USER_FIELDS_PERSONAL" => array(
	),
	"USER_PROPERTY_PERSONAL" => array(
	),
	"GROUP_PROPERTY" => array(
	),
	"GROUP_USE_BAN" => "Y",
	"EDITABLE_FIELDS" => array(
		0 => "PERSONAL_MAILBOX",
	),
	"SHOW_YEAR" => "Y",
	"USER_FIELDS_SEARCH_SIMPLE" => array(
		0 => "PERSONAL_CITY",
	),
	"USER_PROPERTIES_SEARCH_SIMPLE" => array(
	),
	"USER_FIELDS_SEARCH_ADV" => array(
		0 => "PERSONAL_CITY",
	),
	"USER_PROPERTIES_SEARCH_ADV" => array(
	),
	"SONET_USER_FIELDS_LIST" => array(
		0 => "PERSONAL_CITY",
	),
	"SONET_USER_PROPERTY_LIST" => array(
	),
	"SONET_USER_FIELDS_SEARCHABLE" => array(
		0 => "WORK_MAILBOX",
	),
	"SONET_USER_PROPERTY_SEARCHABLE" => array(
	),
	"ALLOW_GROUP_CREATE_REDIRECT_REQUEST" => "Y",
	"ALLOW_RATING_SORT" => "Y",
	"BLOG_GROUP_ID" => "1",
	"ALLOW_POST_MOVE" => "N",
	"BLOG_IMAGE_MAX_WIDTH" => "800",
	"BLOG_IMAGE_MAX_HEIGHT" => "800",
	"BLOG_COMMENT_AJAX_POST" => "Y",
	"BLOG_COMMENT_ALLOW_VIDEO" => "N",
	"BLOG_COMMENT_ALLOW_IMAGE_UPLOAD" => "N",
	"BLOG_SHOW_SPAM" => "N",
	"BLOG_NO_URL_IN_COMMENTS" => "A",
	"BLOG_NO_URL_IN_COMMENTS_AUTHORITY" => "",
	"BLOG_ALLOW_POST_CODE" => "Y",
	"BLOG_USE_GOOGLE_CODE" => "Y",
	"BLOG_USE_CUT" => "Y",
	"FORUM_ID" => "1",
	"FORUM_THEME" => "blue",
	"SHOW_VOTE" => "Y",
	"VOTE_CHANNEL_ID" => "1",
	"VOTE_TEMPLATE" => "light",
	"VOTE_UNIQUE" => array(
		0 => "1",
		1 => "2",
	),
	"VOTE_UNIQUE_IP_DELAY" => "10 D",
	"FORUM_AJAX_POST" => "Y",
	"PHOTO_USER_IBLOCK_TYPE" => "photos",
	"PHOTO_USER_IBLOCK_ID" => "1",
	"PHOTO_GROUP_IBLOCK_TYPE" => "photos",
	"PHOTO_GROUP_IBLOCK_ID" => "1",
	"PHOTO_MODERATION" => "Y",
	"PHOTO_SECTION_PAGE_ELEMENTS" => "15",
	"PHOTO_ELEMENTS_PAGE_ELEMENTS" => "50",
	"PHOTO_ALBUM_PHOTO_THUMBS_SIZE" => "120",
	"PHOTO_THUMBNAIL_SIZE" => "100",
	"PHOTO_ORIGINAL_SIZE" => "1280",
	"PHOTO_UPLOADER_TYPE" => "applet",
	"PHOTO_WATERMARK_MIN_PICTURE_SIZE" => "400",
	"PHOTO_PATH_TO_FONT" => "",
	"PHOTO_SHOW_WATERMARK" => "N",
	"PHOTO_WATERMARK_RULES" => "USER",
	"PHOTO_UPLOAD_MAX_FILESIZE" => "10",
	"PHOTO_USE_RATING" => "N",
	"PHOTO_USE_COMMENTS" => "Y",
	"PHOTO_COMMENTS_TYPE" => "forum",
	"PHOTO_FORUM_ID" => "1",
	"PHOTO_USE_CAPTCHA" => "Y",
	"LOG_PHOTO_COUNT" => "6",
	"LOG_PHOTO_THUMBNAIL_SIZE" => "48",
	"SEARCH_DEFAULT_SORT" => "rank",
	"SEARCH_PAGE_RESULT_COUNT" => "10",
	"SEARCH_TAGS_PAGE_ELEMENTS" => "100",
	"SEARCH_TAGS_PERIOD" => "",
	"SEARCH_TAGS_FONT_MAX" => "50",
	"SEARCH_TAGS_FONT_MIN" => "10",
	"SEARCH_TAGS_COLOR_NEW" => "3E74E6",
	"SEARCH_TAGS_COLOR_OLD" => "C0C0C0",
	"SEARCH_FILTER_NAME" => "sonet_search_filter",
	"SEARCH_FILTER_DATE_NAME" => "sonet_search_filter_date",
	"PHOTO_APPLET_LAYOUT" => "extended",
	"LOG_THUMBNAIL_SIZE" => "",
	"LOG_COMMENT_THUMBNAIL_SIZE" => "",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"user" => "user/#user_id#/",
		"user_friends" => "user/#user_id#/friends/",
		"user_friends_add" => "user/#user_id#/friends/add/",
		"user_friends_delete" => "user/#user_id#/friends/delete/",
		"user_groups" => "user/#user_id#/groups/",
		"user_groups_add" => "user/#user_id#/groups/add/",
		"group_create" => "user/#user_id#/groups/create/",
		"user_profile_edit" => "user/#user_id#/edit/",
		"user_settings_edit" => "user/#user_id#/settings/",
		"user_features" => "user/#user_id#/features/",
		"search" => "search.php",
		"reindex" => "reindex.php",
		"group_content_search" => "group/#group_id#/search/",
		"user_content_search" => "user/#user_id#/search/",
		"group" => "group/#group_id#/",
		"group_search" => "group/search/",
		"group_search_subject" => "group/search/#subject_id#/",
		"group_edit" => "group/#group_id#/edit/",
		"group_delete" => "group/#group_id#/delete/",
		"group_request_search" => "group/#group_id#/user_search/",
		"user_request_group" => "group/#group_id#/user_request/",
		"group_requests" => "group/#group_id#/requests/",
		"group_requests_out" => "group/#group_id#/requests_out/",
		"group_mods" => "group/#group_id#/moderators/",
		"group_users" => "group/#group_id#/users/",
		"group_ban" => "group/#group_id#/ban/",
		"user_leave_group" => "group/#group_id#/user_leave/",
		"group_features" => "group/#group_id#/features/",
		"group_log" => "group/#group_id#/log/",
		"group_request_user" => "group/#group_id#/user/#user_id#/request/",
		"group_request_group_search" => "group/#user_id#/group_search/",
		"mail" => "mail/",
		"message_form" => "messages/form/#user_id#/",
		"message_form_mess" => "messages/chat/#user_id#/#message_id#/",
		"user_ban" => "messages/ban/",
		"messages_chat" => "messages/chat/#user_id#/",
		"messages_input" => "messages/input/",
		"messages_input_user" => "messages/input/#user_id#/",
		"messages_output" => "messages/output/",
		"messages_output_user" => "messages/output/#user_id#/",
		"messages_users" => "messages/",
		"messages_users_messages" => "messages/#user_id#/",
		"log" => "log/",
		"activity" => "user/#user_id#/activity/",
		"subscribe" => "subscribe/",
		"user_subscribe" => "user/#user_id#/subscribe/",
		"group_subscribe" => "group/#group_id#/subscribe/",
		"user_photo" => "user/#user_id#/photo/",
		"user_calendar" => "user/#user_id#/calendar/",
		"user_files" => "user/#user_id#/files/lib/#path#",
		"group_photo" => "group/#group_id#/photo/",
		"group_forum" => "group/#group_id#/forum/",
		"group_calendar" => "group/#group_id#/calendar/",
		"group_files" => "group/#group_id#/files/#path#",
		"user_blog" => "user/#user_id#/blog/",
		"user_blog_post_edit" => "user/#user_id#/blog/edit/#post_id#/",
		"user_blog_rss" => "user/#user_id#/blog/rss/#type#/",
		"user_blog_draft" => "user/#user_id#/blog/draft/",
		"user_blog_post" => "user/#user_id#/blog/#post_id#/",
		"user_blog_moderation" => "user/#user_id#/blog/moderation/",
		"user_forum" => "user/#user_id#/forum/",
		"user_forum_topic_edit" => "user/#user_id#/forum/edit/#topic_id#/",
		"user_forum_topic" => "user/#user_id#/forum/#topic_id#/",
		"group_blog" => "group/#group_id#/blog/",
		"group_blog_post_edit" => "group/#group_id#/blog/edit/#post_id#/",
		"group_blog_rss" => "group/#group_id#/blog/rss/#type#/",
		"group_blog_draft" => "group/#group_id#/blog/draft/",
		"group_blog_post" => "group/#group_id#/blog/#post_id#/",
		"group_blog_moderation" => "group/#group_id#/blog/moderation/",
		"group_forum_topic_edit" => "group/#group_id#/forum/edit/#topic_id#/",
		"group_forum_topic" => "group/#group_id#/forum/#topic_id#/",
		"bizproc" => "bizproc/",
		"bizproc_edit" => "bizproc/#task_id#/",
		"video_call" => "video/#user_id#/",
	)
	),
	false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>